CLIENT_VERSION = 4

MAX_ARMY_NAME_LEN = 20

RECAPTCHA2_ENABLED = false	
// RECAPTCHA2_SITEKEY = '????' // only for client side
// RECAPTCHA2_SERVERKEY = '????' // only for server side

BATTLE_CELLS_WIDTH = 7
BATTLE_CELLS_HEIGHT = 6

BATTLE_CELL_WIDTH = 80
BATTLE_CELL_HEIGHT = 80

